# Generated by Django 6.0.4 on 2026-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_team_leader_email_team_leader_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="leader_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
