# Generated by Django 6.0.4 on 2026-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_leader_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="project_file",
            field=models.FileField(blank=True, null=True, upload_to="submissions/"),
        ),
    ]
