# Generated by Django 6.0.4 on 2026-04-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_submission_project_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={
                "verbose_name": "Project Submission",
                "verbose_name_plural": "Project Submissions",
            },
        ),
    ]
