# Generated by Django 6.0.4 on 2026-05-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_judgeassignment_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Approved",
                max_length=20,
            ),
        ),
    ]
